deployment_environment: production
s3_bucket: eurtisan-uploads
mollie_test_mode: false
sendcloud_force_unstamped_letter: false
email_delivery_provider: brevo
email_smtp_host: ""
app_container_name: eurtisan-app
