deployment_environment: staging
release_registry_self_hosted: true
release_registry: registry-staging.eurtisan.eu
release_image_repository: registry-staging.eurtisan.eu/eurtisan/app
registry_push_access_key_id: "{{ staging_registry_push_username }}"
registry_push_secret_key: "{{ staging_registry_push_password }}"
registry_pull_access_key_id: "{{ staging_registry_pull_username }}"
registry_pull_secret_key: "{{ staging_registry_pull_password }}"
registry_http_secret: "{{ staging_registry_http_secret }}"
garage_enabled: true
garage_public_domain: s3-staging.eurtisan.eu
s3_endpoint: http://garage:3900
s3_public_endpoint: https://s3-staging.eurtisan.eu
s3_region: garage
s3_bucket: eurtisan-staging-uploads
mollie_test_mode: true
sendcloud_force_unstamped_letter: true
email_delivery_provider: smtp
email_smtp_host: mailpit
email_smtp_port: "1025"
email_from_address: noreply@staging.eurtisan.eu
app_container_name: eurtisan-app-staging
faro_sample_rate: "1"
