#!/bin/sh
# Garage initialization script for local development
# Creates bucket, access key, and grants permissions using the Garage CLI
# via docker exec. Idempotent — safe to re-run.

set -e

CONTAINER_NAME="eurtisan-garage"
BUCKET_NAME="${GARAGE_BUCKET_NAME:-eurtisan-uploads}"
KEY_NAME="${GARAGE_KEY_NAME:-dev-key}"
ENV_FILE=".env.garage"

echo "[garage-init] Waiting for Garage container to be healthy..."
for i in $(seq 1 60); do
  if docker inspect --format='{{.State.Health.Status}}' "$CONTAINER_NAME" 2>/dev/null | grep -q "healthy"; then
    break
  fi
  if [ "$i" -eq 60 ]; then
    echo "[garage-init] Timeout waiting for Garage to become healthy."
    exit 1
  fi
  sleep 1
done

echo "[garage-init] Garage is healthy."

garage_exec() {
  docker exec "$CONTAINER_NAME" /garage "$@" 2>/dev/null
}

# Get node ID
NODE_ID=$(garage_exec status | grep -E '^[a-f0-9]{16}' | head -1 | awk '{print $1}')
if [ -z "$NODE_ID" ]; then
  echo "[garage-init] Could not determine node ID."
  exit 1
fi

echo "[garage-init] Node ID: $NODE_ID"

# Configure layout if not already done
LAYOUT=$(garage_exec layout show || true)
if echo "$LAYOUT" | grep -q "NO ROLE ASSIGNED"; then
  echo "[garage-init] Assigning role to node..."
  garage_exec layout assign "$NODE_ID" -z z1 -c 1TB >/dev/null
  VERSION=$(echo "$LAYOUT" | grep "Current cluster layout version:" | awk '{print $NF}')
  NEW_VERSION=$((VERSION + 1))
  garage_exec layout apply --version "$NEW_VERSION" >/dev/null
  echo "[garage-init] Layout applied."
else
  echo "[garage-init] Layout already configured."
fi

# Create bucket if not exists
if ! garage_exec bucket list | grep -q "$BUCKET_NAME"; then
  echo "[garage-init] Creating bucket '$BUCKET_NAME'..."
  garage_exec bucket create "$BUCKET_NAME" >/dev/null
  echo "[garage-init] Bucket created."
else
  echo "[garage-init] Bucket '$BUCKET_NAME' already exists."
fi

# Create key if not exists
if ! garage_exec key list | grep -q "$KEY_NAME"; then
  echo "[garage-init] Creating access key '$KEY_NAME'..."
  garage_exec key create "$KEY_NAME" >/dev/null
  echo "[garage-init] Access key created."
else
  echo "[garage-init] Access key '$KEY_NAME' already exists."
fi

# Grant key permissions on bucket
echo "[garage-init] Granting key access to bucket..."
garage_exec bucket allow "$BUCKET_NAME" --key "$KEY_NAME" --read --write --owner >/dev/null

# Enable public website access on bucket
echo "[garage-init] Enabling public website access on bucket..."
garage_exec bucket website "$BUCKET_NAME" --allow >/dev/null

# Retrieve credentials
KEY_INFO=$(garage_exec key info --show-secret "$KEY_NAME")
ACCESS_KEY_ID=$(echo "$KEY_INFO" | grep -E '^Key ID:' | sed 's/.*: *//')
SECRET_KEY=$(echo "$KEY_INFO" | grep -E '^Secret key:' | sed 's/.*: *//')

# Write credentials to .env.garage if changed
WRITE_ENV=false
if [ ! -f "$ENV_FILE" ]; then
  WRITE_ENV=true
elif ! grep -q "S3_ACCESS_KEY_ID=${ACCESS_KEY_ID}" "$ENV_FILE" 2>/dev/null; then
  WRITE_ENV=true
elif ! grep -q "AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}" "$ENV_FILE" 2>/dev/null; then
  WRITE_ENV=true
fi

if [ "$WRITE_ENV" = "true" ]; then
  echo "[garage-init] Writing credentials to $ENV_FILE..."
  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts/garage-init.sh — do not edit manually
S3_ACCESS_KEY_ID=${ACCESS_KEY_ID}
S3_SECRET_ACCESS_KEY=${SECRET_KEY}
IMGPROXY_S3_ACCESS_KEY_ID=${ACCESS_KEY_ID}
IMGPROXY_S3_SECRET_ACCESS_KEY=${SECRET_KEY}
AWS_ACCESS_KEY_ID=${ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY=${SECRET_KEY}
EOF
  echo "[garage-init] Credentials written. Recreating app, imgproxy, and email-outbox-worker..."
  docker compose up -d app imgproxy email-outbox-worker >/dev/null 2>&1 || true
else
  echo "[garage-init] Credentials unchanged."
fi

# Configure CORS on the bucket for browser uploads
echo "[garage-init] Configuring CORS on bucket..."
docker compose exec -T app bun run scripts/setup-garage-cors.ts 2>/dev/null || echo "[garage-init] Warning: CORS setup skipped (app container may not be ready yet)"

echo ""
echo "========================================"
echo "Garage initialization complete!"
echo "Bucket: ${BUCKET_NAME}"
echo "Access Key ID: ${ACCESS_KEY_ID}"
echo "========================================"
