/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MollieMockOauthRouteImport } from './routes/mollie-mock-oauth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as SellIndexRouteImport } from './routes/sell/index'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as CreatorIndexRouteImport } from './routes/creator/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as StudioShopIdRouteImport } from './routes/studio/$shopId'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ShopsShopSlugRouteImport } from './routes/shops/$shopSlug'
import { Route as RobotsTxtRouteImport } from './routes/robots.txt'
import { Route as OrdersPlatformOrderIdRouteImport } from './routes/orders.$platformOrderId'
import { Route as InvoicesInvoiceIdRouteImport } from './routes/invoices.$invoiceId'
import { Route as DisputesDisputeIdRouteImport } from './routes/disputes.$disputeId'
import { Route as CreatorShopRouteImport } from './routes/creator/shop'
import { Route as CreatorProductsRouteImport } from './routes/creator/products'
import { Route as CreatorPayoutsRouteImport } from './routes/creator/payouts'
import { Route as CategoryAllRouteImport } from './routes/category/all'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as ApiUnsubscribeRouteImport } from './routes/api/unsubscribe'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as ApiImageRouteImport } from './routes/api/image'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiBackupReportRouteImport } from './routes/api/backup-report'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminShopsRouteImport } from './routes/admin/shops'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAuditLogRouteImport } from './routes/admin/audit-log'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountSecurityRouteImport } from './routes/account/security'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as StudioShopIdIndexRouteImport } from './routes/studio/$shopId.index'
import { Route as ShopsShopSlugIndexRouteImport } from './routes/shops/$shopSlug.index'
import { Route as OrdersPlatformOrderIdIndexRouteImport } from './routes/orders.$platformOrderId.index'
import { Route as CreatorProductsIndexRouteImport } from './routes/creator/products/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders.index'
import { Route as AdminDisputesIndexRouteImport } from './routes/admin/disputes.index'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders.index'
import { Route as StudioShopIdSettingsRouteImport } from './routes/studio/$shopId.settings'
import { Route as StudioShopIdOrdersRouteImport } from './routes/studio/$shopId.orders'
import { Route as StudioShopIdCustomersRouteImport } from './routes/studio/$shopId.customers'
import { Route as SellStatusShopIdRouteImport } from './routes/sell/status/$shopId'
import { Route as SellOnboardingDraftIdRouteImport } from './routes/sell/onboarding/$draftId'
import { Route as OrdersPlatformOrderIdSuccessRouteImport } from './routes/orders.$platformOrderId.success'
import { Route as CreatorProductsNewRouteImport } from './routes/creator/products/new'
import { Route as ApiWebhooksSendcloudRouteImport } from './routes/api/webhooks/sendcloud'
import { Route as ApiWebhooksMollieChargebackRouteImport } from './routes/api/webhooks/mollie-chargeback'
import { Route as ApiWebhooksMollieRouteImport } from './routes/api/webhooks/mollie'
import { Route as ApiWebhooksBrevoRouteImport } from './routes/api/webhooks/brevo'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health.ready'
import { Route as ApiHealthLiveRouteImport } from './routes/api/health.live'
import { Route as ApiHealthDepsRouteImport } from './routes/api/health.deps'
import { Route as ApiE2eMockPaymentStatusRouteImport } from './routes/api/e2e/mock-payment-status'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminOrdersPlatformOrderIdRouteImport } from './routes/admin/orders.$platformOrderId'
import { Route as AdminDisputesDisputeIdRouteImport } from './routes/admin/disputes/$disputeId'
import { Route as AccountOrdersOrderNumberRouteImport } from './routes/account/orders.$orderNumber'
import { Route as StudioShopIdOrdersIndexRouteImport } from './routes/studio/$shopId.orders.index'
import { Route as StudioShopIdCustomersIndexRouteImport } from './routes/studio/$shopId.customers.index'
import { Route as SellOnboardingDraftIdIndexRouteImport } from './routes/sell/onboarding/$draftId/index'
import { Route as StudioShopIdSettingsTaxRouteImport } from './routes/studio/$shopId.settings.tax'
import { Route as StudioShopIdOrdersShopOrderIdRouteImport } from './routes/studio/$shopId.orders.$shopOrderId'
import { Route as StudioShopIdCustomersCustomerHashRouteImport } from './routes/studio/$shopId.customers.$customerHash'
import { Route as ShopsShopSlugProductsProductSlugRouteImport } from './routes/shops/$shopSlug.products.$productSlug'
import { Route as SellOnboardingDraftIdVisualsRouteImport } from './routes/sell/onboarding/$draftId/visuals'
import { Route as SellOnboardingDraftIdStoryRouteImport } from './routes/sell/onboarding/$draftId/story'
import { Route as SellOnboardingDraftIdSocialsRouteImport } from './routes/sell/onboarding/$draftId/socials'
import { Route as SellOnboardingDraftIdReviewRouteImport } from './routes/sell/onboarding/$draftId/review'
import { Route as SellOnboardingDraftIdPoliciesRouteImport } from './routes/sell/onboarding/$draftId/policies'
import { Route as SellOnboardingDraftIdLocationRouteImport } from './routes/sell/onboarding/$draftId/location'
import { Route as SellOnboardingDraftIdListingRouteImport } from './routes/sell/onboarding/$draftId/listing'
import { Route as SellOnboardingDraftIdIdentityRouteImport } from './routes/sell/onboarding/$draftId/identity'
import { Route as CreatorProductsProductIdEditRouteImport } from './routes/creator/products/$productId/edit'
import { Route as ApiShopsShopIdSettingsRouteImport } from './routes/api/shops/$shopId/settings'
import { Route as ApiShopsShopIdProductsRouteImport } from './routes/api/shops/$shopId/products'
import { Route as ApiShopsShopIdOrdersRouteImport } from './routes/api/shops/$shopId/orders'
import { Route as ApiShopsShopIdDashboardRouteImport } from './routes/api/shops/$shopId/dashboard'
import { Route as ApiAuthMollieCallbackRouteImport } from './routes/api/auth/mollie/callback'
import { Route as ApiAdminPayoutsPayoutIdRouteImport } from './routes/api/admin/payouts.$payoutId'
import { Route as ApiShopsShopIdProductsProductIdRouteImport } from './routes/api/shops/$shopId/products.$productId'
import { Route as ApiShopsShopIdOrdersShopOrderIdRouteImport } from './routes/api/shops/$shopId/orders.$shopOrderId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MollieMockOauthRoute = MollieMockOauthRouteImport.update({
  id: '/mollie-mock-oauth',
  path: '/mollie-mock-oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrdersRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioShopIdRoute = StudioShopIdRouteImport.update({
  id: '/$shopId',
  path: '/$shopId',
  getParentRoute: () => StudioRouteRoute,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopSlugRoute = ShopsShopSlugRouteImport.update({
  id: '/shops/$shopSlug',
  path: '/shops/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsTxtRoute = RobotsTxtRouteImport.update({
  id: '/robots/txt',
  path: '/robots/txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersPlatformOrderIdRoute = OrdersPlatformOrderIdRouteImport.update({
  id: '/$platformOrderId',
  path: '/$platformOrderId',
  getParentRoute: () => OrdersRoute,
} as any)
const InvoicesInvoiceIdRoute = InvoicesInvoiceIdRouteImport.update({
  id: '/invoices/$invoiceId',
  path: '/invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DisputesDisputeIdRoute = DisputesDisputeIdRouteImport.update({
  id: '/disputes/$disputeId',
  path: '/disputes/$disputeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorShopRoute = CreatorShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProductsRoute = CreatorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorPayoutsRoute = CreatorPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => CreatorRoute,
} as any)
const CategoryAllRoute = CategoryAllRouteImport.update({
  id: '/category/all',
  path: '/category/all',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUnsubscribeRoute = ApiUnsubscribeRouteImport.update({
  id: '/api/unsubscribe',
  path: '/api/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBackupReportRoute = ApiBackupReportRouteImport.update({
  id: '/api/backup-report',
  path: '/api/backup-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/shops',
  path: '/shops',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioShopIdIndexRoute = StudioShopIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioShopIdRoute,
} as any)
const ShopsShopSlugIndexRoute = ShopsShopSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopsShopSlugRoute,
} as any)
const OrdersPlatformOrderIdIndexRoute =
  OrdersPlatformOrderIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => OrdersPlatformOrderIdRoute,
  } as any)
const CreatorProductsIndexRoute = CreatorProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorProductsRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminDisputesIndexRoute = AdminDisputesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDisputesRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const StudioShopIdSettingsRoute = StudioShopIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioShopIdRoute,
} as any)
const StudioShopIdOrdersRoute = StudioShopIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StudioShopIdRoute,
} as any)
const StudioShopIdCustomersRoute = StudioShopIdCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => StudioShopIdRoute,
} as any)
const SellStatusShopIdRoute = SellStatusShopIdRouteImport.update({
  id: '/sell/status/$shopId',
  path: '/sell/status/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellOnboardingDraftIdRoute = SellOnboardingDraftIdRouteImport.update({
  id: '/sell/onboarding/$draftId',
  path: '/sell/onboarding/$draftId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersPlatformOrderIdSuccessRoute =
  OrdersPlatformOrderIdSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => OrdersPlatformOrderIdRoute,
  } as any)
const CreatorProductsNewRoute = CreatorProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CreatorProductsRoute,
} as any)
const ApiWebhooksSendcloudRoute = ApiWebhooksSendcloudRouteImport.update({
  id: '/api/webhooks/sendcloud',
  path: '/api/webhooks/sendcloud',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksMollieChargebackRoute =
  ApiWebhooksMollieChargebackRouteImport.update({
    id: '/api/webhooks/mollie-chargeback',
    path: '/api/webhooks/mollie-chargeback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWebhooksMollieRoute = ApiWebhooksMollieRouteImport.update({
  id: '/api/webhooks/mollie',
  path: '/api/webhooks/mollie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksBrevoRoute = ApiWebhooksBrevoRouteImport.update({
  id: '/api/webhooks/brevo',
  path: '/api/webhooks/brevo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthLiveRoute = ApiHealthLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiHealthDepsRoute = ApiHealthDepsRouteImport.update({
  id: '/deps',
  path: '/deps',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiE2eMockPaymentStatusRoute = ApiE2eMockPaymentStatusRouteImport.update({
  id: '/api/e2e/mock-payment-status',
  path: '/api/e2e/mock-payment-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersPlatformOrderIdRoute =
  AdminOrdersPlatformOrderIdRouteImport.update({
    id: '/$platformOrderId',
    path: '/$platformOrderId',
    getParentRoute: () => AdminOrdersRoute,
  } as any)
const AdminDisputesDisputeIdRoute = AdminDisputesDisputeIdRouteImport.update({
  id: '/$disputeId',
  path: '/$disputeId',
  getParentRoute: () => AdminDisputesRoute,
} as any)
const AccountOrdersOrderNumberRoute =
  AccountOrdersOrderNumberRouteImport.update({
    id: '/$orderNumber',
    path: '/$orderNumber',
    getParentRoute: () => AccountOrdersRoute,
  } as any)
const StudioShopIdOrdersIndexRoute = StudioShopIdOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioShopIdOrdersRoute,
} as any)
const StudioShopIdCustomersIndexRoute =
  StudioShopIdCustomersIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudioShopIdCustomersRoute,
  } as any)
const SellOnboardingDraftIdIndexRoute =
  SellOnboardingDraftIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const StudioShopIdSettingsTaxRoute = StudioShopIdSettingsTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => StudioShopIdSettingsRoute,
} as any)
const StudioShopIdOrdersShopOrderIdRoute =
  StudioShopIdOrdersShopOrderIdRouteImport.update({
    id: '/$shopOrderId',
    path: '/$shopOrderId',
    getParentRoute: () => StudioShopIdOrdersRoute,
  } as any)
const StudioShopIdCustomersCustomerHashRoute =
  StudioShopIdCustomersCustomerHashRouteImport.update({
    id: '/$customerHash',
    path: '/$customerHash',
    getParentRoute: () => StudioShopIdCustomersRoute,
  } as any)
const ShopsShopSlugProductsProductSlugRoute =
  ShopsShopSlugProductsProductSlugRouteImport.update({
    id: '/products/$productSlug',
    path: '/products/$productSlug',
    getParentRoute: () => ShopsShopSlugRoute,
  } as any)
const SellOnboardingDraftIdVisualsRoute =
  SellOnboardingDraftIdVisualsRouteImport.update({
    id: '/visuals',
    path: '/visuals',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const SellOnboardingDraftIdStoryRoute =
  SellOnboardingDraftIdStoryRouteImport.update({
    id: '/story',
    path: '/story',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const SellOnboardingDraftIdSocialsRoute =
  SellOnboardingDraftIdSocialsRouteImport.update({
    id: '/socials',
    path: '/socials',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const SellOnboardingDraftIdReviewRoute =
  SellOnboardingDraftIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const SellOnboardingDraftIdPoliciesRoute =
  SellOnboardingDraftIdPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const SellOnboardingDraftIdLocationRoute =
  SellOnboardingDraftIdLocationRouteImport.update({
    id: '/location',
    path: '/location',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const SellOnboardingDraftIdListingRoute =
  SellOnboardingDraftIdListingRouteImport.update({
    id: '/listing',
    path: '/listing',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const SellOnboardingDraftIdIdentityRoute =
  SellOnboardingDraftIdIdentityRouteImport.update({
    id: '/identity',
    path: '/identity',
    getParentRoute: () => SellOnboardingDraftIdRoute,
  } as any)
const CreatorProductsProductIdEditRoute =
  CreatorProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => CreatorProductsRoute,
  } as any)
const ApiShopsShopIdSettingsRoute = ApiShopsShopIdSettingsRouteImport.update({
  id: '/api/shops/$shopId/settings',
  path: '/api/shops/$shopId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopsShopIdProductsRoute = ApiShopsShopIdProductsRouteImport.update({
  id: '/api/shops/$shopId/products',
  path: '/api/shops/$shopId/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopsShopIdOrdersRoute = ApiShopsShopIdOrdersRouteImport.update({
  id: '/api/shops/$shopId/orders',
  path: '/api/shops/$shopId/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopsShopIdDashboardRoute = ApiShopsShopIdDashboardRouteImport.update({
  id: '/api/shops/$shopId/dashboard',
  path: '/api/shops/$shopId/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthMollieCallbackRoute = ApiAuthMollieCallbackRouteImport.update({
  id: '/api/auth/mollie/callback',
  path: '/api/auth/mollie/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPayoutsPayoutIdRoute = ApiAdminPayoutsPayoutIdRouteImport.update({
  id: '/api/admin/payouts/$payoutId',
  path: '/api/admin/payouts/$payoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopsShopIdProductsProductIdRoute =
  ApiShopsShopIdProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => ApiShopsShopIdProductsRoute,
  } as any)
const ApiShopsShopIdOrdersShopOrderIdRoute =
  ApiShopsShopIdOrdersShopOrderIdRouteImport.update({
    id: '/$shopOrderId',
    path: '/$shopOrderId',
    getParentRoute: () => ApiShopsShopIdOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mollie-mock-oauth': typeof MollieMockOauthRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/backup-report': typeof ApiBackupReportRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/image': typeof ApiImageRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/products': typeof ApiProductsRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/category/$slug': typeof CategorySlugRoute
  '/category/all': typeof CategoryAllRoute
  '/creator/payouts': typeof CreatorPayoutsRoute
  '/creator/products': typeof CreatorProductsRouteWithChildren
  '/creator/shop': typeof CreatorShopRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/orders/$platformOrderId': typeof OrdersPlatformOrderIdRouteWithChildren
  '/robots/txt': typeof RobotsTxtRoute
  '/shops/$shopSlug': typeof ShopsShopSlugRouteWithChildren
  '/sitemap/xml': typeof SitemapXmlRoute
  '/studio/$shopId': typeof StudioShopIdRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/sell/': typeof SellIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/orders/$platformOrderId': typeof AdminOrdersPlatformOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/mock-payment-status': typeof ApiE2eMockPaymentStatusRoute
  '/api/health/deps': typeof ApiHealthDepsRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/webhooks/brevo': typeof ApiWebhooksBrevoRoute
  '/api/webhooks/mollie': typeof ApiWebhooksMollieRoute
  '/api/webhooks/mollie-chargeback': typeof ApiWebhooksMollieChargebackRoute
  '/api/webhooks/sendcloud': typeof ApiWebhooksSendcloudRoute
  '/creator/products/new': typeof CreatorProductsNewRoute
  '/orders/$platformOrderId/success': typeof OrdersPlatformOrderIdSuccessRoute
  '/sell/onboarding/$draftId': typeof SellOnboardingDraftIdRouteWithChildren
  '/sell/status/$shopId': typeof SellStatusShopIdRoute
  '/studio/$shopId/customers': typeof StudioShopIdCustomersRouteWithChildren
  '/studio/$shopId/orders': typeof StudioShopIdOrdersRouteWithChildren
  '/studio/$shopId/settings': typeof StudioShopIdSettingsRouteWithChildren
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/disputes/': typeof AdminDisputesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/creator/products/': typeof CreatorProductsIndexRoute
  '/orders/$platformOrderId/': typeof OrdersPlatformOrderIdIndexRoute
  '/shops/$shopSlug/': typeof ShopsShopSlugIndexRoute
  '/studio/$shopId/': typeof StudioShopIdIndexRoute
  '/api/admin/payouts/$payoutId': typeof ApiAdminPayoutsPayoutIdRoute
  '/api/auth/mollie/callback': typeof ApiAuthMollieCallbackRoute
  '/api/shops/$shopId/dashboard': typeof ApiShopsShopIdDashboardRoute
  '/api/shops/$shopId/orders': typeof ApiShopsShopIdOrdersRouteWithChildren
  '/api/shops/$shopId/products': typeof ApiShopsShopIdProductsRouteWithChildren
  '/api/shops/$shopId/settings': typeof ApiShopsShopIdSettingsRoute
  '/creator/products/$productId/edit': typeof CreatorProductsProductIdEditRoute
  '/sell/onboarding/$draftId/identity': typeof SellOnboardingDraftIdIdentityRoute
  '/sell/onboarding/$draftId/listing': typeof SellOnboardingDraftIdListingRoute
  '/sell/onboarding/$draftId/location': typeof SellOnboardingDraftIdLocationRoute
  '/sell/onboarding/$draftId/policies': typeof SellOnboardingDraftIdPoliciesRoute
  '/sell/onboarding/$draftId/review': typeof SellOnboardingDraftIdReviewRoute
  '/sell/onboarding/$draftId/socials': typeof SellOnboardingDraftIdSocialsRoute
  '/sell/onboarding/$draftId/story': typeof SellOnboardingDraftIdStoryRoute
  '/sell/onboarding/$draftId/visuals': typeof SellOnboardingDraftIdVisualsRoute
  '/shops/$shopSlug/products/$productSlug': typeof ShopsShopSlugProductsProductSlugRoute
  '/studio/$shopId/customers/$customerHash': typeof StudioShopIdCustomersCustomerHashRoute
  '/studio/$shopId/orders/$shopOrderId': typeof StudioShopIdOrdersShopOrderIdRoute
  '/studio/$shopId/settings/tax': typeof StudioShopIdSettingsTaxRoute
  '/sell/onboarding/$draftId/': typeof SellOnboardingDraftIdIndexRoute
  '/studio/$shopId/customers/': typeof StudioShopIdCustomersIndexRoute
  '/studio/$shopId/orders/': typeof StudioShopIdOrdersIndexRoute
  '/api/shops/$shopId/orders/$shopOrderId': typeof ApiShopsShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/products/$productId': typeof ApiShopsShopIdProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mollie-mock-oauth': typeof MollieMockOauthRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/backup-report': typeof ApiBackupReportRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/image': typeof ApiImageRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/products': typeof ApiProductsRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/category/$slug': typeof CategorySlugRoute
  '/category/all': typeof CategoryAllRoute
  '/creator/payouts': typeof CreatorPayoutsRoute
  '/creator/shop': typeof CreatorShopRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/robots/txt': typeof RobotsTxtRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/orders': typeof OrdersIndexRoute
  '/sell': typeof SellIndexRoute
  '/studio': typeof StudioIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/orders/$platformOrderId': typeof AdminOrdersPlatformOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/mock-payment-status': typeof ApiE2eMockPaymentStatusRoute
  '/api/health/deps': typeof ApiHealthDepsRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/webhooks/brevo': typeof ApiWebhooksBrevoRoute
  '/api/webhooks/mollie': typeof ApiWebhooksMollieRoute
  '/api/webhooks/mollie-chargeback': typeof ApiWebhooksMollieChargebackRoute
  '/api/webhooks/sendcloud': typeof ApiWebhooksSendcloudRoute
  '/creator/products/new': typeof CreatorProductsNewRoute
  '/orders/$platformOrderId/success': typeof OrdersPlatformOrderIdSuccessRoute
  '/sell/status/$shopId': typeof SellStatusShopIdRoute
  '/studio/$shopId/settings': typeof StudioShopIdSettingsRouteWithChildren
  '/account/orders': typeof AccountOrdersIndexRoute
  '/admin/disputes': typeof AdminDisputesIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/creator/products': typeof CreatorProductsIndexRoute
  '/orders/$platformOrderId': typeof OrdersPlatformOrderIdIndexRoute
  '/shops/$shopSlug': typeof ShopsShopSlugIndexRoute
  '/studio/$shopId': typeof StudioShopIdIndexRoute
  '/api/admin/payouts/$payoutId': typeof ApiAdminPayoutsPayoutIdRoute
  '/api/auth/mollie/callback': typeof ApiAuthMollieCallbackRoute
  '/api/shops/$shopId/dashboard': typeof ApiShopsShopIdDashboardRoute
  '/api/shops/$shopId/orders': typeof ApiShopsShopIdOrdersRouteWithChildren
  '/api/shops/$shopId/products': typeof ApiShopsShopIdProductsRouteWithChildren
  '/api/shops/$shopId/settings': typeof ApiShopsShopIdSettingsRoute
  '/creator/products/$productId/edit': typeof CreatorProductsProductIdEditRoute
  '/sell/onboarding/$draftId/identity': typeof SellOnboardingDraftIdIdentityRoute
  '/sell/onboarding/$draftId/listing': typeof SellOnboardingDraftIdListingRoute
  '/sell/onboarding/$draftId/location': typeof SellOnboardingDraftIdLocationRoute
  '/sell/onboarding/$draftId/policies': typeof SellOnboardingDraftIdPoliciesRoute
  '/sell/onboarding/$draftId/review': typeof SellOnboardingDraftIdReviewRoute
  '/sell/onboarding/$draftId/socials': typeof SellOnboardingDraftIdSocialsRoute
  '/sell/onboarding/$draftId/story': typeof SellOnboardingDraftIdStoryRoute
  '/sell/onboarding/$draftId/visuals': typeof SellOnboardingDraftIdVisualsRoute
  '/shops/$shopSlug/products/$productSlug': typeof ShopsShopSlugProductsProductSlugRoute
  '/studio/$shopId/customers/$customerHash': typeof StudioShopIdCustomersCustomerHashRoute
  '/studio/$shopId/orders/$shopOrderId': typeof StudioShopIdOrdersShopOrderIdRoute
  '/studio/$shopId/settings/tax': typeof StudioShopIdSettingsTaxRoute
  '/sell/onboarding/$draftId': typeof SellOnboardingDraftIdIndexRoute
  '/studio/$shopId/customers': typeof StudioShopIdCustomersIndexRoute
  '/studio/$shopId/orders': typeof StudioShopIdOrdersIndexRoute
  '/api/shops/$shopId/orders/$shopOrderId': typeof ApiShopsShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/products/$productId': typeof ApiShopsShopIdProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/cookies': typeof CookiesRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/mollie-mock-oauth': typeof MollieMockOauthRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/security': typeof AccountSecurityRoute
  '/account/settings': typeof AccountSettingsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/backup-report': typeof ApiBackupReportRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/api/image': typeof ApiImageRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/api/products': typeof ApiProductsRoute
  '/api/unsubscribe': typeof ApiUnsubscribeRoute
  '/category/$slug': typeof CategorySlugRoute
  '/category/all': typeof CategoryAllRoute
  '/creator/payouts': typeof CreatorPayoutsRoute
  '/creator/products': typeof CreatorProductsRouteWithChildren
  '/creator/shop': typeof CreatorShopRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/invoices/$invoiceId': typeof InvoicesInvoiceIdRoute
  '/orders/$platformOrderId': typeof OrdersPlatformOrderIdRouteWithChildren
  '/robots/txt': typeof RobotsTxtRoute
  '/shops/$shopSlug': typeof ShopsShopSlugRouteWithChildren
  '/sitemap/xml': typeof SitemapXmlRoute
  '/studio/$shopId': typeof StudioShopIdRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/orders/': typeof OrdersIndexRoute
  '/sell/': typeof SellIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/account/orders/$orderNumber': typeof AccountOrdersOrderNumberRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/orders/$platformOrderId': typeof AdminOrdersPlatformOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/e2e/mock-payment-status': typeof ApiE2eMockPaymentStatusRoute
  '/api/health/deps': typeof ApiHealthDepsRoute
  '/api/health/live': typeof ApiHealthLiveRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/webhooks/brevo': typeof ApiWebhooksBrevoRoute
  '/api/webhooks/mollie': typeof ApiWebhooksMollieRoute
  '/api/webhooks/mollie-chargeback': typeof ApiWebhooksMollieChargebackRoute
  '/api/webhooks/sendcloud': typeof ApiWebhooksSendcloudRoute
  '/creator/products/new': typeof CreatorProductsNewRoute
  '/orders/$platformOrderId/success': typeof OrdersPlatformOrderIdSuccessRoute
  '/sell/onboarding/$draftId': typeof SellOnboardingDraftIdRouteWithChildren
  '/sell/status/$shopId': typeof SellStatusShopIdRoute
  '/studio/$shopId/customers': typeof StudioShopIdCustomersRouteWithChildren
  '/studio/$shopId/orders': typeof StudioShopIdOrdersRouteWithChildren
  '/studio/$shopId/settings': typeof StudioShopIdSettingsRouteWithChildren
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/admin/disputes/': typeof AdminDisputesIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/creator/products/': typeof CreatorProductsIndexRoute
  '/orders/$platformOrderId/': typeof OrdersPlatformOrderIdIndexRoute
  '/shops/$shopSlug/': typeof ShopsShopSlugIndexRoute
  '/studio/$shopId/': typeof StudioShopIdIndexRoute
  '/api/admin/payouts/$payoutId': typeof ApiAdminPayoutsPayoutIdRoute
  '/api/auth/mollie/callback': typeof ApiAuthMollieCallbackRoute
  '/api/shops/$shopId/dashboard': typeof ApiShopsShopIdDashboardRoute
  '/api/shops/$shopId/orders': typeof ApiShopsShopIdOrdersRouteWithChildren
  '/api/shops/$shopId/products': typeof ApiShopsShopIdProductsRouteWithChildren
  '/api/shops/$shopId/settings': typeof ApiShopsShopIdSettingsRoute
  '/creator/products/$productId/edit': typeof CreatorProductsProductIdEditRoute
  '/sell/onboarding/$draftId/identity': typeof SellOnboardingDraftIdIdentityRoute
  '/sell/onboarding/$draftId/listing': typeof SellOnboardingDraftIdListingRoute
  '/sell/onboarding/$draftId/location': typeof SellOnboardingDraftIdLocationRoute
  '/sell/onboarding/$draftId/policies': typeof SellOnboardingDraftIdPoliciesRoute
  '/sell/onboarding/$draftId/review': typeof SellOnboardingDraftIdReviewRoute
  '/sell/onboarding/$draftId/socials': typeof SellOnboardingDraftIdSocialsRoute
  '/sell/onboarding/$draftId/story': typeof SellOnboardingDraftIdStoryRoute
  '/sell/onboarding/$draftId/visuals': typeof SellOnboardingDraftIdVisualsRoute
  '/shops/$shopSlug/products/$productSlug': typeof ShopsShopSlugProductsProductSlugRoute
  '/studio/$shopId/customers/$customerHash': typeof StudioShopIdCustomersCustomerHashRoute
  '/studio/$shopId/orders/$shopOrderId': typeof StudioShopIdOrdersShopOrderIdRoute
  '/studio/$shopId/settings/tax': typeof StudioShopIdSettingsTaxRoute
  '/sell/onboarding/$draftId/': typeof SellOnboardingDraftIdIndexRoute
  '/studio/$shopId/customers/': typeof StudioShopIdCustomersIndexRoute
  '/studio/$shopId/orders/': typeof StudioShopIdOrdersIndexRoute
  '/api/shops/$shopId/orders/$shopOrderId': typeof ApiShopsShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/products/$productId': typeof ApiShopsShopIdProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/studio'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/cookies'
    | '/creator'
    | '/forbidden'
    | '/forgot-password'
    | '/mollie-mock-oauth'
    | '/notifications'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signin'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/account/orders'
    | '/account/security'
    | '/account/settings'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/disputes'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/shops'
    | '/admin/users'
    | '/api/backup-report'
    | '/api/health'
    | '/api/image'
    | '/api/metrics'
    | '/api/products'
    | '/api/unsubscribe'
    | '/category/$slug'
    | '/category/all'
    | '/creator/payouts'
    | '/creator/products'
    | '/creator/shop'
    | '/disputes/$disputeId'
    | '/invoices/$invoiceId'
    | '/orders/$platformOrderId'
    | '/robots/txt'
    | '/shops/$shopSlug'
    | '/sitemap/xml'
    | '/studio/$shopId'
    | '/account/'
    | '/admin/'
    | '/creator/'
    | '/orders/'
    | '/sell/'
    | '/studio/'
    | '/account/orders/$orderNumber'
    | '/admin/disputes/$disputeId'
    | '/admin/orders/$platformOrderId'
    | '/api/auth/$'
    | '/api/e2e/mock-payment-status'
    | '/api/health/deps'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/webhooks/brevo'
    | '/api/webhooks/mollie'
    | '/api/webhooks/mollie-chargeback'
    | '/api/webhooks/sendcloud'
    | '/creator/products/new'
    | '/orders/$platformOrderId/success'
    | '/sell/onboarding/$draftId'
    | '/sell/status/$shopId'
    | '/studio/$shopId/customers'
    | '/studio/$shopId/orders'
    | '/studio/$shopId/settings'
    | '/account/orders/'
    | '/admin/disputes/'
    | '/admin/orders/'
    | '/creator/products/'
    | '/orders/$platformOrderId/'
    | '/shops/$shopSlug/'
    | '/studio/$shopId/'
    | '/api/admin/payouts/$payoutId'
    | '/api/auth/mollie/callback'
    | '/api/shops/$shopId/dashboard'
    | '/api/shops/$shopId/orders'
    | '/api/shops/$shopId/products'
    | '/api/shops/$shopId/settings'
    | '/creator/products/$productId/edit'
    | '/sell/onboarding/$draftId/identity'
    | '/sell/onboarding/$draftId/listing'
    | '/sell/onboarding/$draftId/location'
    | '/sell/onboarding/$draftId/policies'
    | '/sell/onboarding/$draftId/review'
    | '/sell/onboarding/$draftId/socials'
    | '/sell/onboarding/$draftId/story'
    | '/sell/onboarding/$draftId/visuals'
    | '/shops/$shopSlug/products/$productSlug'
    | '/studio/$shopId/customers/$customerHash'
    | '/studio/$shopId/orders/$shopOrderId'
    | '/studio/$shopId/settings/tax'
    | '/sell/onboarding/$draftId/'
    | '/studio/$shopId/customers/'
    | '/studio/$shopId/orders/'
    | '/api/shops/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/cookies'
    | '/forbidden'
    | '/forgot-password'
    | '/mollie-mock-oauth'
    | '/notifications'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signin'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/account/security'
    | '/account/settings'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/shops'
    | '/admin/users'
    | '/api/backup-report'
    | '/api/health'
    | '/api/image'
    | '/api/metrics'
    | '/api/products'
    | '/api/unsubscribe'
    | '/category/$slug'
    | '/category/all'
    | '/creator/payouts'
    | '/creator/shop'
    | '/disputes/$disputeId'
    | '/invoices/$invoiceId'
    | '/robots/txt'
    | '/sitemap/xml'
    | '/account'
    | '/admin'
    | '/creator'
    | '/orders'
    | '/sell'
    | '/studio'
    | '/account/orders/$orderNumber'
    | '/admin/disputes/$disputeId'
    | '/admin/orders/$platformOrderId'
    | '/api/auth/$'
    | '/api/e2e/mock-payment-status'
    | '/api/health/deps'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/webhooks/brevo'
    | '/api/webhooks/mollie'
    | '/api/webhooks/mollie-chargeback'
    | '/api/webhooks/sendcloud'
    | '/creator/products/new'
    | '/orders/$platformOrderId/success'
    | '/sell/status/$shopId'
    | '/studio/$shopId/settings'
    | '/account/orders'
    | '/admin/disputes'
    | '/admin/orders'
    | '/creator/products'
    | '/orders/$platformOrderId'
    | '/shops/$shopSlug'
    | '/studio/$shopId'
    | '/api/admin/payouts/$payoutId'
    | '/api/auth/mollie/callback'
    | '/api/shops/$shopId/dashboard'
    | '/api/shops/$shopId/orders'
    | '/api/shops/$shopId/products'
    | '/api/shops/$shopId/settings'
    | '/creator/products/$productId/edit'
    | '/sell/onboarding/$draftId/identity'
    | '/sell/onboarding/$draftId/listing'
    | '/sell/onboarding/$draftId/location'
    | '/sell/onboarding/$draftId/policies'
    | '/sell/onboarding/$draftId/review'
    | '/sell/onboarding/$draftId/socials'
    | '/sell/onboarding/$draftId/story'
    | '/sell/onboarding/$draftId/visuals'
    | '/shops/$shopSlug/products/$productSlug'
    | '/studio/$shopId/customers/$customerHash'
    | '/studio/$shopId/orders/$shopOrderId'
    | '/studio/$shopId/settings/tax'
    | '/sell/onboarding/$draftId'
    | '/studio/$shopId/customers'
    | '/studio/$shopId/orders'
    | '/api/shops/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/studio'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/cookies'
    | '/creator'
    | '/forbidden'
    | '/forgot-password'
    | '/mollie-mock-oauth'
    | '/notifications'
    | '/orders'
    | '/privacy'
    | '/reset-password'
    | '/search'
    | '/signin'
    | '/terms'
    | '/unsubscribe'
    | '/verify-email'
    | '/account/orders'
    | '/account/security'
    | '/account/settings'
    | '/admin/audit-log'
    | '/admin/categories'
    | '/admin/disputes'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/shops'
    | '/admin/users'
    | '/api/backup-report'
    | '/api/health'
    | '/api/image'
    | '/api/metrics'
    | '/api/products'
    | '/api/unsubscribe'
    | '/category/$slug'
    | '/category/all'
    | '/creator/payouts'
    | '/creator/products'
    | '/creator/shop'
    | '/disputes/$disputeId'
    | '/invoices/$invoiceId'
    | '/orders/$platformOrderId'
    | '/robots/txt'
    | '/shops/$shopSlug'
    | '/sitemap/xml'
    | '/studio/$shopId'
    | '/account/'
    | '/admin/'
    | '/creator/'
    | '/orders/'
    | '/sell/'
    | '/studio/'
    | '/account/orders/$orderNumber'
    | '/admin/disputes/$disputeId'
    | '/admin/orders/$platformOrderId'
    | '/api/auth/$'
    | '/api/e2e/mock-payment-status'
    | '/api/health/deps'
    | '/api/health/live'
    | '/api/health/ready'
    | '/api/webhooks/brevo'
    | '/api/webhooks/mollie'
    | '/api/webhooks/mollie-chargeback'
    | '/api/webhooks/sendcloud'
    | '/creator/products/new'
    | '/orders/$platformOrderId/success'
    | '/sell/onboarding/$draftId'
    | '/sell/status/$shopId'
    | '/studio/$shopId/customers'
    | '/studio/$shopId/orders'
    | '/studio/$shopId/settings'
    | '/account/orders/'
    | '/admin/disputes/'
    | '/admin/orders/'
    | '/creator/products/'
    | '/orders/$platformOrderId/'
    | '/shops/$shopSlug/'
    | '/studio/$shopId/'
    | '/api/admin/payouts/$payoutId'
    | '/api/auth/mollie/callback'
    | '/api/shops/$shopId/dashboard'
    | '/api/shops/$shopId/orders'
    | '/api/shops/$shopId/products'
    | '/api/shops/$shopId/settings'
    | '/creator/products/$productId/edit'
    | '/sell/onboarding/$draftId/identity'
    | '/sell/onboarding/$draftId/listing'
    | '/sell/onboarding/$draftId/location'
    | '/sell/onboarding/$draftId/policies'
    | '/sell/onboarding/$draftId/review'
    | '/sell/onboarding/$draftId/socials'
    | '/sell/onboarding/$draftId/story'
    | '/sell/onboarding/$draftId/visuals'
    | '/shops/$shopSlug/products/$productSlug'
    | '/studio/$shopId/customers/$customerHash'
    | '/studio/$shopId/orders/$shopOrderId'
    | '/studio/$shopId/settings/tax'
    | '/sell/onboarding/$draftId/'
    | '/studio/$shopId/customers/'
    | '/studio/$shopId/orders/'
    | '/api/shops/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CookiesRoute: typeof CookiesRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  MollieMockOauthRoute: typeof MollieMockOauthRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  ApiBackupReportRoute: typeof ApiBackupReportRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  ApiImageRoute: typeof ApiImageRoute
  ApiMetricsRoute: typeof ApiMetricsRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiUnsubscribeRoute: typeof ApiUnsubscribeRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CategoryAllRoute: typeof CategoryAllRoute
  DisputesDisputeIdRoute: typeof DisputesDisputeIdRoute
  InvoicesInvoiceIdRoute: typeof InvoicesInvoiceIdRoute
  RobotsTxtRoute: typeof RobotsTxtRoute
  ShopsShopSlugRoute: typeof ShopsShopSlugRouteWithChildren
  SitemapXmlRoute: typeof SitemapXmlRoute
  AccountIndexRoute: typeof AccountIndexRoute
  SellIndexRoute: typeof SellIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiE2eMockPaymentStatusRoute: typeof ApiE2eMockPaymentStatusRoute
  ApiWebhooksBrevoRoute: typeof ApiWebhooksBrevoRoute
  ApiWebhooksMollieRoute: typeof ApiWebhooksMollieRoute
  ApiWebhooksMollieChargebackRoute: typeof ApiWebhooksMollieChargebackRoute
  ApiWebhooksSendcloudRoute: typeof ApiWebhooksSendcloudRoute
  SellOnboardingDraftIdRoute: typeof SellOnboardingDraftIdRouteWithChildren
  SellStatusShopIdRoute: typeof SellStatusShopIdRoute
  ApiAdminPayoutsPayoutIdRoute: typeof ApiAdminPayoutsPayoutIdRoute
  ApiAuthMollieCallbackRoute: typeof ApiAuthMollieCallbackRoute
  ApiShopsShopIdDashboardRoute: typeof ApiShopsShopIdDashboardRoute
  ApiShopsShopIdOrdersRoute: typeof ApiShopsShopIdOrdersRouteWithChildren
  ApiShopsShopIdProductsRoute: typeof ApiShopsShopIdProductsRouteWithChildren
  ApiShopsShopIdSettingsRoute: typeof ApiShopsShopIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mollie-mock-oauth': {
      id: '/mollie-mock-oauth'
      path: '/mollie-mock-oauth'
      fullPath: '/mollie-mock-oauth'
      preLoaderRoute: typeof MollieMockOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$shopId': {
      id: '/studio/$shopId'
      path: '/$shopId'
      fullPath: '/studio/$shopId'
      preLoaderRoute: typeof StudioShopIdRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopSlug': {
      id: '/shops/$shopSlug'
      path: '/shops/$shopSlug'
      fullPath: '/shops/$shopSlug'
      preLoaderRoute: typeof ShopsShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots/txt': {
      id: '/robots/txt'
      path: '/robots/txt'
      fullPath: '/robots/txt'
      preLoaderRoute: typeof RobotsTxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$platformOrderId': {
      id: '/orders/$platformOrderId'
      path: '/$platformOrderId'
      fullPath: '/orders/$platformOrderId'
      preLoaderRoute: typeof OrdersPlatformOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/invoices/$invoiceId': {
      id: '/invoices/$invoiceId'
      path: '/invoices/$invoiceId'
      fullPath: '/invoices/$invoiceId'
      preLoaderRoute: typeof InvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disputes/$disputeId': {
      id: '/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof DisputesDisputeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/shop': {
      id: '/creator/shop'
      path: '/shop'
      fullPath: '/creator/shop'
      preLoaderRoute: typeof CreatorShopRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/products': {
      id: '/creator/products'
      path: '/products'
      fullPath: '/creator/products'
      preLoaderRoute: typeof CreatorProductsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/payouts': {
      id: '/creator/payouts'
      path: '/payouts'
      fullPath: '/creator/payouts'
      preLoaderRoute: typeof CreatorPayoutsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/category/all': {
      id: '/category/all'
      path: '/category/all'
      fullPath: '/category/all'
      preLoaderRoute: typeof CategoryAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/unsubscribe': {
      id: '/api/unsubscribe'
      path: '/api/unsubscribe'
      fullPath: '/api/unsubscribe'
      preLoaderRoute: typeof ApiUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/backup-report': {
      id: '/api/backup-report'
      path: '/api/backup-report'
      fullPath: '/api/backup-report'
      preLoaderRoute: typeof ApiBackupReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$shopId/': {
      id: '/studio/$shopId/'
      path: '/'
      fullPath: '/studio/$shopId/'
      preLoaderRoute: typeof StudioShopIdIndexRouteImport
      parentRoute: typeof StudioShopIdRoute
    }
    '/shops/$shopSlug/': {
      id: '/shops/$shopSlug/'
      path: '/'
      fullPath: '/shops/$shopSlug/'
      preLoaderRoute: typeof ShopsShopSlugIndexRouteImport
      parentRoute: typeof ShopsShopSlugRoute
    }
    '/orders/$platformOrderId/': {
      id: '/orders/$platformOrderId/'
      path: '/'
      fullPath: '/orders/$platformOrderId/'
      preLoaderRoute: typeof OrdersPlatformOrderIdIndexRouteImport
      parentRoute: typeof OrdersPlatformOrderIdRoute
    }
    '/creator/products/': {
      id: '/creator/products/'
      path: '/'
      fullPath: '/creator/products/'
      preLoaderRoute: typeof CreatorProductsIndexRouteImport
      parentRoute: typeof CreatorProductsRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/disputes/': {
      id: '/admin/disputes/'
      path: '/'
      fullPath: '/admin/disputes/'
      preLoaderRoute: typeof AdminDisputesIndexRouteImport
      parentRoute: typeof AdminDisputesRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/studio/$shopId/settings': {
      id: '/studio/$shopId/settings'
      path: '/settings'
      fullPath: '/studio/$shopId/settings'
      preLoaderRoute: typeof StudioShopIdSettingsRouteImport
      parentRoute: typeof StudioShopIdRoute
    }
    '/studio/$shopId/orders': {
      id: '/studio/$shopId/orders'
      path: '/orders'
      fullPath: '/studio/$shopId/orders'
      preLoaderRoute: typeof StudioShopIdOrdersRouteImport
      parentRoute: typeof StudioShopIdRoute
    }
    '/studio/$shopId/customers': {
      id: '/studio/$shopId/customers'
      path: '/customers'
      fullPath: '/studio/$shopId/customers'
      preLoaderRoute: typeof StudioShopIdCustomersRouteImport
      parentRoute: typeof StudioShopIdRoute
    }
    '/sell/status/$shopId': {
      id: '/sell/status/$shopId'
      path: '/sell/status/$shopId'
      fullPath: '/sell/status/$shopId'
      preLoaderRoute: typeof SellStatusShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/onboarding/$draftId': {
      id: '/sell/onboarding/$draftId'
      path: '/sell/onboarding/$draftId'
      fullPath: '/sell/onboarding/$draftId'
      preLoaderRoute: typeof SellOnboardingDraftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$platformOrderId/success': {
      id: '/orders/$platformOrderId/success'
      path: '/success'
      fullPath: '/orders/$platformOrderId/success'
      preLoaderRoute: typeof OrdersPlatformOrderIdSuccessRouteImport
      parentRoute: typeof OrdersPlatformOrderIdRoute
    }
    '/creator/products/new': {
      id: '/creator/products/new'
      path: '/new'
      fullPath: '/creator/products/new'
      preLoaderRoute: typeof CreatorProductsNewRouteImport
      parentRoute: typeof CreatorProductsRoute
    }
    '/api/webhooks/sendcloud': {
      id: '/api/webhooks/sendcloud'
      path: '/api/webhooks/sendcloud'
      fullPath: '/api/webhooks/sendcloud'
      preLoaderRoute: typeof ApiWebhooksSendcloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mollie-chargeback': {
      id: '/api/webhooks/mollie-chargeback'
      path: '/api/webhooks/mollie-chargeback'
      fullPath: '/api/webhooks/mollie-chargeback'
      preLoaderRoute: typeof ApiWebhooksMollieChargebackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/mollie': {
      id: '/api/webhooks/mollie'
      path: '/api/webhooks/mollie'
      fullPath: '/api/webhooks/mollie'
      preLoaderRoute: typeof ApiWebhooksMollieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/brevo': {
      id: '/api/webhooks/brevo'
      path: '/api/webhooks/brevo'
      fullPath: '/api/webhooks/brevo'
      preLoaderRoute: typeof ApiWebhooksBrevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/live': {
      id: '/api/health/live'
      path: '/live'
      fullPath: '/api/health/live'
      preLoaderRoute: typeof ApiHealthLiveRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/health/deps': {
      id: '/api/health/deps'
      path: '/deps'
      fullPath: '/api/health/deps'
      preLoaderRoute: typeof ApiHealthDepsRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/e2e/mock-payment-status': {
      id: '/api/e2e/mock-payment-status'
      path: '/api/e2e/mock-payment-status'
      fullPath: '/api/e2e/mock-payment-status'
      preLoaderRoute: typeof ApiE2eMockPaymentStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$platformOrderId': {
      id: '/admin/orders/$platformOrderId'
      path: '/$platformOrderId'
      fullPath: '/admin/orders/$platformOrderId'
      preLoaderRoute: typeof AdminOrdersPlatformOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/disputes/$disputeId': {
      id: '/admin/disputes/$disputeId'
      path: '/$disputeId'
      fullPath: '/admin/disputes/$disputeId'
      preLoaderRoute: typeof AdminDisputesDisputeIdRouteImport
      parentRoute: typeof AdminDisputesRoute
    }
    '/account/orders/$orderNumber': {
      id: '/account/orders/$orderNumber'
      path: '/$orderNumber'
      fullPath: '/account/orders/$orderNumber'
      preLoaderRoute: typeof AccountOrdersOrderNumberRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/studio/$shopId/orders/': {
      id: '/studio/$shopId/orders/'
      path: '/'
      fullPath: '/studio/$shopId/orders/'
      preLoaderRoute: typeof StudioShopIdOrdersIndexRouteImport
      parentRoute: typeof StudioShopIdOrdersRoute
    }
    '/studio/$shopId/customers/': {
      id: '/studio/$shopId/customers/'
      path: '/'
      fullPath: '/studio/$shopId/customers/'
      preLoaderRoute: typeof StudioShopIdCustomersIndexRouteImport
      parentRoute: typeof StudioShopIdCustomersRoute
    }
    '/sell/onboarding/$draftId/': {
      id: '/sell/onboarding/$draftId/'
      path: '/'
      fullPath: '/sell/onboarding/$draftId/'
      preLoaderRoute: typeof SellOnboardingDraftIdIndexRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/studio/$shopId/settings/tax': {
      id: '/studio/$shopId/settings/tax'
      path: '/tax'
      fullPath: '/studio/$shopId/settings/tax'
      preLoaderRoute: typeof StudioShopIdSettingsTaxRouteImport
      parentRoute: typeof StudioShopIdSettingsRoute
    }
    '/studio/$shopId/orders/$shopOrderId': {
      id: '/studio/$shopId/orders/$shopOrderId'
      path: '/$shopOrderId'
      fullPath: '/studio/$shopId/orders/$shopOrderId'
      preLoaderRoute: typeof StudioShopIdOrdersShopOrderIdRouteImport
      parentRoute: typeof StudioShopIdOrdersRoute
    }
    '/studio/$shopId/customers/$customerHash': {
      id: '/studio/$shopId/customers/$customerHash'
      path: '/$customerHash'
      fullPath: '/studio/$shopId/customers/$customerHash'
      preLoaderRoute: typeof StudioShopIdCustomersCustomerHashRouteImport
      parentRoute: typeof StudioShopIdCustomersRoute
    }
    '/shops/$shopSlug/products/$productSlug': {
      id: '/shops/$shopSlug/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/shops/$shopSlug/products/$productSlug'
      preLoaderRoute: typeof ShopsShopSlugProductsProductSlugRouteImport
      parentRoute: typeof ShopsShopSlugRoute
    }
    '/sell/onboarding/$draftId/visuals': {
      id: '/sell/onboarding/$draftId/visuals'
      path: '/visuals'
      fullPath: '/sell/onboarding/$draftId/visuals'
      preLoaderRoute: typeof SellOnboardingDraftIdVisualsRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/sell/onboarding/$draftId/story': {
      id: '/sell/onboarding/$draftId/story'
      path: '/story'
      fullPath: '/sell/onboarding/$draftId/story'
      preLoaderRoute: typeof SellOnboardingDraftIdStoryRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/sell/onboarding/$draftId/socials': {
      id: '/sell/onboarding/$draftId/socials'
      path: '/socials'
      fullPath: '/sell/onboarding/$draftId/socials'
      preLoaderRoute: typeof SellOnboardingDraftIdSocialsRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/sell/onboarding/$draftId/review': {
      id: '/sell/onboarding/$draftId/review'
      path: '/review'
      fullPath: '/sell/onboarding/$draftId/review'
      preLoaderRoute: typeof SellOnboardingDraftIdReviewRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/sell/onboarding/$draftId/policies': {
      id: '/sell/onboarding/$draftId/policies'
      path: '/policies'
      fullPath: '/sell/onboarding/$draftId/policies'
      preLoaderRoute: typeof SellOnboardingDraftIdPoliciesRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/sell/onboarding/$draftId/location': {
      id: '/sell/onboarding/$draftId/location'
      path: '/location'
      fullPath: '/sell/onboarding/$draftId/location'
      preLoaderRoute: typeof SellOnboardingDraftIdLocationRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/sell/onboarding/$draftId/listing': {
      id: '/sell/onboarding/$draftId/listing'
      path: '/listing'
      fullPath: '/sell/onboarding/$draftId/listing'
      preLoaderRoute: typeof SellOnboardingDraftIdListingRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/sell/onboarding/$draftId/identity': {
      id: '/sell/onboarding/$draftId/identity'
      path: '/identity'
      fullPath: '/sell/onboarding/$draftId/identity'
      preLoaderRoute: typeof SellOnboardingDraftIdIdentityRouteImport
      parentRoute: typeof SellOnboardingDraftIdRoute
    }
    '/creator/products/$productId/edit': {
      id: '/creator/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/creator/products/$productId/edit'
      preLoaderRoute: typeof CreatorProductsProductIdEditRouteImport
      parentRoute: typeof CreatorProductsRoute
    }
    '/api/shops/$shopId/settings': {
      id: '/api/shops/$shopId/settings'
      path: '/api/shops/$shopId/settings'
      fullPath: '/api/shops/$shopId/settings'
      preLoaderRoute: typeof ApiShopsShopIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shops/$shopId/products': {
      id: '/api/shops/$shopId/products'
      path: '/api/shops/$shopId/products'
      fullPath: '/api/shops/$shopId/products'
      preLoaderRoute: typeof ApiShopsShopIdProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shops/$shopId/orders': {
      id: '/api/shops/$shopId/orders'
      path: '/api/shops/$shopId/orders'
      fullPath: '/api/shops/$shopId/orders'
      preLoaderRoute: typeof ApiShopsShopIdOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shops/$shopId/dashboard': {
      id: '/api/shops/$shopId/dashboard'
      path: '/api/shops/$shopId/dashboard'
      fullPath: '/api/shops/$shopId/dashboard'
      preLoaderRoute: typeof ApiShopsShopIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/mollie/callback': {
      id: '/api/auth/mollie/callback'
      path: '/api/auth/mollie/callback'
      fullPath: '/api/auth/mollie/callback'
      preLoaderRoute: typeof ApiAuthMollieCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payouts/$payoutId': {
      id: '/api/admin/payouts/$payoutId'
      path: '/api/admin/payouts/$payoutId'
      fullPath: '/api/admin/payouts/$payoutId'
      preLoaderRoute: typeof ApiAdminPayoutsPayoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shops/$shopId/products/$productId': {
      id: '/api/shops/$shopId/products/$productId'
      path: '/$productId'
      fullPath: '/api/shops/$shopId/products/$productId'
      preLoaderRoute: typeof ApiShopsShopIdProductsProductIdRouteImport
      parentRoute: typeof ApiShopsShopIdProductsRoute
    }
    '/api/shops/$shopId/orders/$shopOrderId': {
      id: '/api/shops/$shopId/orders/$shopOrderId'
      path: '/$shopOrderId'
      fullPath: '/api/shops/$shopId/orders/$shopOrderId'
      preLoaderRoute: typeof ApiShopsShopIdOrdersShopOrderIdRouteImport
      parentRoute: typeof ApiShopsShopIdOrdersRoute
    }
  }
}

interface AdminDisputesRouteChildren {
  AdminDisputesDisputeIdRoute: typeof AdminDisputesDisputeIdRoute
  AdminDisputesIndexRoute: typeof AdminDisputesIndexRoute
}

const AdminDisputesRouteChildren: AdminDisputesRouteChildren = {
  AdminDisputesDisputeIdRoute: AdminDisputesDisputeIdRoute,
  AdminDisputesIndexRoute: AdminDisputesIndexRoute,
}

const AdminDisputesRouteWithChildren = AdminDisputesRoute._addFileChildren(
  AdminDisputesRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersPlatformOrderIdRoute: typeof AdminOrdersPlatformOrderIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersPlatformOrderIdRoute: AdminOrdersPlatformOrderIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminDisputesRoute: typeof AdminDisputesRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminShopsRoute: typeof AdminShopsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminDisputesRoute: AdminDisputesRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminShopsRoute: AdminShopsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface StudioShopIdCustomersRouteChildren {
  StudioShopIdCustomersCustomerHashRoute: typeof StudioShopIdCustomersCustomerHashRoute
  StudioShopIdCustomersIndexRoute: typeof StudioShopIdCustomersIndexRoute
}

const StudioShopIdCustomersRouteChildren: StudioShopIdCustomersRouteChildren = {
  StudioShopIdCustomersCustomerHashRoute:
    StudioShopIdCustomersCustomerHashRoute,
  StudioShopIdCustomersIndexRoute: StudioShopIdCustomersIndexRoute,
}

const StudioShopIdCustomersRouteWithChildren =
  StudioShopIdCustomersRoute._addFileChildren(
    StudioShopIdCustomersRouteChildren,
  )

interface StudioShopIdOrdersRouteChildren {
  StudioShopIdOrdersShopOrderIdRoute: typeof StudioShopIdOrdersShopOrderIdRoute
  StudioShopIdOrdersIndexRoute: typeof StudioShopIdOrdersIndexRoute
}

const StudioShopIdOrdersRouteChildren: StudioShopIdOrdersRouteChildren = {
  StudioShopIdOrdersShopOrderIdRoute: StudioShopIdOrdersShopOrderIdRoute,
  StudioShopIdOrdersIndexRoute: StudioShopIdOrdersIndexRoute,
}

const StudioShopIdOrdersRouteWithChildren =
  StudioShopIdOrdersRoute._addFileChildren(StudioShopIdOrdersRouteChildren)

interface StudioShopIdSettingsRouteChildren {
  StudioShopIdSettingsTaxRoute: typeof StudioShopIdSettingsTaxRoute
}

const StudioShopIdSettingsRouteChildren: StudioShopIdSettingsRouteChildren = {
  StudioShopIdSettingsTaxRoute: StudioShopIdSettingsTaxRoute,
}

const StudioShopIdSettingsRouteWithChildren =
  StudioShopIdSettingsRoute._addFileChildren(StudioShopIdSettingsRouteChildren)

interface StudioShopIdRouteChildren {
  StudioShopIdCustomersRoute: typeof StudioShopIdCustomersRouteWithChildren
  StudioShopIdOrdersRoute: typeof StudioShopIdOrdersRouteWithChildren
  StudioShopIdSettingsRoute: typeof StudioShopIdSettingsRouteWithChildren
  StudioShopIdIndexRoute: typeof StudioShopIdIndexRoute
}

const StudioShopIdRouteChildren: StudioShopIdRouteChildren = {
  StudioShopIdCustomersRoute: StudioShopIdCustomersRouteWithChildren,
  StudioShopIdOrdersRoute: StudioShopIdOrdersRouteWithChildren,
  StudioShopIdSettingsRoute: StudioShopIdSettingsRouteWithChildren,
  StudioShopIdIndexRoute: StudioShopIdIndexRoute,
}

const StudioShopIdRouteWithChildren = StudioShopIdRoute._addFileChildren(
  StudioShopIdRouteChildren,
)

interface StudioRouteRouteChildren {
  StudioShopIdRoute: typeof StudioShopIdRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioShopIdRoute: StudioShopIdRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

interface CreatorProductsRouteChildren {
  CreatorProductsNewRoute: typeof CreatorProductsNewRoute
  CreatorProductsIndexRoute: typeof CreatorProductsIndexRoute
  CreatorProductsProductIdEditRoute: typeof CreatorProductsProductIdEditRoute
}

const CreatorProductsRouteChildren: CreatorProductsRouteChildren = {
  CreatorProductsNewRoute: CreatorProductsNewRoute,
  CreatorProductsIndexRoute: CreatorProductsIndexRoute,
  CreatorProductsProductIdEditRoute: CreatorProductsProductIdEditRoute,
}

const CreatorProductsRouteWithChildren = CreatorProductsRoute._addFileChildren(
  CreatorProductsRouteChildren,
)

interface CreatorRouteChildren {
  CreatorPayoutsRoute: typeof CreatorPayoutsRoute
  CreatorProductsRoute: typeof CreatorProductsRouteWithChildren
  CreatorShopRoute: typeof CreatorShopRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorPayoutsRoute: CreatorPayoutsRoute,
  CreatorProductsRoute: CreatorProductsRouteWithChildren,
  CreatorShopRoute: CreatorShopRoute,
  CreatorIndexRoute: CreatorIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface OrdersPlatformOrderIdRouteChildren {
  OrdersPlatformOrderIdSuccessRoute: typeof OrdersPlatformOrderIdSuccessRoute
  OrdersPlatformOrderIdIndexRoute: typeof OrdersPlatformOrderIdIndexRoute
}

const OrdersPlatformOrderIdRouteChildren: OrdersPlatformOrderIdRouteChildren = {
  OrdersPlatformOrderIdSuccessRoute: OrdersPlatformOrderIdSuccessRoute,
  OrdersPlatformOrderIdIndexRoute: OrdersPlatformOrderIdIndexRoute,
}

const OrdersPlatformOrderIdRouteWithChildren =
  OrdersPlatformOrderIdRoute._addFileChildren(
    OrdersPlatformOrderIdRouteChildren,
  )

interface OrdersRouteChildren {
  OrdersPlatformOrderIdRoute: typeof OrdersPlatformOrderIdRouteWithChildren
  OrdersIndexRoute: typeof OrdersIndexRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersPlatformOrderIdRoute: OrdersPlatformOrderIdRouteWithChildren,
  OrdersIndexRoute: OrdersIndexRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface AccountOrdersRouteChildren {
  AccountOrdersOrderNumberRoute: typeof AccountOrdersOrderNumberRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderNumberRoute: AccountOrdersOrderNumberRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface ApiHealthRouteChildren {
  ApiHealthDepsRoute: typeof ApiHealthDepsRoute
  ApiHealthLiveRoute: typeof ApiHealthLiveRoute
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthDepsRoute: ApiHealthDepsRoute,
  ApiHealthLiveRoute: ApiHealthLiveRoute,
  ApiHealthReadyRoute: ApiHealthReadyRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

interface ShopsShopSlugRouteChildren {
  ShopsShopSlugIndexRoute: typeof ShopsShopSlugIndexRoute
  ShopsShopSlugProductsProductSlugRoute: typeof ShopsShopSlugProductsProductSlugRoute
}

const ShopsShopSlugRouteChildren: ShopsShopSlugRouteChildren = {
  ShopsShopSlugIndexRoute: ShopsShopSlugIndexRoute,
  ShopsShopSlugProductsProductSlugRoute: ShopsShopSlugProductsProductSlugRoute,
}

const ShopsShopSlugRouteWithChildren = ShopsShopSlugRoute._addFileChildren(
  ShopsShopSlugRouteChildren,
)

interface SellOnboardingDraftIdRouteChildren {
  SellOnboardingDraftIdIdentityRoute: typeof SellOnboardingDraftIdIdentityRoute
  SellOnboardingDraftIdListingRoute: typeof SellOnboardingDraftIdListingRoute
  SellOnboardingDraftIdLocationRoute: typeof SellOnboardingDraftIdLocationRoute
  SellOnboardingDraftIdPoliciesRoute: typeof SellOnboardingDraftIdPoliciesRoute
  SellOnboardingDraftIdReviewRoute: typeof SellOnboardingDraftIdReviewRoute
  SellOnboardingDraftIdSocialsRoute: typeof SellOnboardingDraftIdSocialsRoute
  SellOnboardingDraftIdStoryRoute: typeof SellOnboardingDraftIdStoryRoute
  SellOnboardingDraftIdVisualsRoute: typeof SellOnboardingDraftIdVisualsRoute
  SellOnboardingDraftIdIndexRoute: typeof SellOnboardingDraftIdIndexRoute
}

const SellOnboardingDraftIdRouteChildren: SellOnboardingDraftIdRouteChildren = {
  SellOnboardingDraftIdIdentityRoute: SellOnboardingDraftIdIdentityRoute,
  SellOnboardingDraftIdListingRoute: SellOnboardingDraftIdListingRoute,
  SellOnboardingDraftIdLocationRoute: SellOnboardingDraftIdLocationRoute,
  SellOnboardingDraftIdPoliciesRoute: SellOnboardingDraftIdPoliciesRoute,
  SellOnboardingDraftIdReviewRoute: SellOnboardingDraftIdReviewRoute,
  SellOnboardingDraftIdSocialsRoute: SellOnboardingDraftIdSocialsRoute,
  SellOnboardingDraftIdStoryRoute: SellOnboardingDraftIdStoryRoute,
  SellOnboardingDraftIdVisualsRoute: SellOnboardingDraftIdVisualsRoute,
  SellOnboardingDraftIdIndexRoute: SellOnboardingDraftIdIndexRoute,
}

const SellOnboardingDraftIdRouteWithChildren =
  SellOnboardingDraftIdRoute._addFileChildren(
    SellOnboardingDraftIdRouteChildren,
  )

interface ApiShopsShopIdOrdersRouteChildren {
  ApiShopsShopIdOrdersShopOrderIdRoute: typeof ApiShopsShopIdOrdersShopOrderIdRoute
}

const ApiShopsShopIdOrdersRouteChildren: ApiShopsShopIdOrdersRouteChildren = {
  ApiShopsShopIdOrdersShopOrderIdRoute: ApiShopsShopIdOrdersShopOrderIdRoute,
}

const ApiShopsShopIdOrdersRouteWithChildren =
  ApiShopsShopIdOrdersRoute._addFileChildren(ApiShopsShopIdOrdersRouteChildren)

interface ApiShopsShopIdProductsRouteChildren {
  ApiShopsShopIdProductsProductIdRoute: typeof ApiShopsShopIdProductsProductIdRoute
}

const ApiShopsShopIdProductsRouteChildren: ApiShopsShopIdProductsRouteChildren =
  {
    ApiShopsShopIdProductsProductIdRoute: ApiShopsShopIdProductsProductIdRoute,
  }

const ApiShopsShopIdProductsRouteWithChildren =
  ApiShopsShopIdProductsRoute._addFileChildren(
    ApiShopsShopIdProductsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  StudioRouteRoute: StudioRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CookiesRoute: CookiesRoute,
  CreatorRoute: CreatorRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  MollieMockOauthRoute: MollieMockOauthRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  ApiBackupReportRoute: ApiBackupReportRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  ApiImageRoute: ApiImageRoute,
  ApiMetricsRoute: ApiMetricsRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiUnsubscribeRoute: ApiUnsubscribeRoute,
  CategorySlugRoute: CategorySlugRoute,
  CategoryAllRoute: CategoryAllRoute,
  DisputesDisputeIdRoute: DisputesDisputeIdRoute,
  InvoicesInvoiceIdRoute: InvoicesInvoiceIdRoute,
  RobotsTxtRoute: RobotsTxtRoute,
  ShopsShopSlugRoute: ShopsShopSlugRouteWithChildren,
  SitemapXmlRoute: SitemapXmlRoute,
  AccountIndexRoute: AccountIndexRoute,
  SellIndexRoute: SellIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiE2eMockPaymentStatusRoute: ApiE2eMockPaymentStatusRoute,
  ApiWebhooksBrevoRoute: ApiWebhooksBrevoRoute,
  ApiWebhooksMollieRoute: ApiWebhooksMollieRoute,
  ApiWebhooksMollieChargebackRoute: ApiWebhooksMollieChargebackRoute,
  ApiWebhooksSendcloudRoute: ApiWebhooksSendcloudRoute,
  SellOnboardingDraftIdRoute: SellOnboardingDraftIdRouteWithChildren,
  SellStatusShopIdRoute: SellStatusShopIdRoute,
  ApiAdminPayoutsPayoutIdRoute: ApiAdminPayoutsPayoutIdRoute,
  ApiAuthMollieCallbackRoute: ApiAuthMollieCallbackRoute,
  ApiShopsShopIdDashboardRoute: ApiShopsShopIdDashboardRoute,
  ApiShopsShopIdOrdersRoute: ApiShopsShopIdOrdersRouteWithChildren,
  ApiShopsShopIdProductsRoute: ApiShopsShopIdProductsRouteWithChildren,
  ApiShopsShopIdSettingsRoute: ApiShopsShopIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
