/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as StudioShopIdRouteImport } from './routes/studio/$shopId'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as ShopsShopSlugRouteImport } from './routes/shops/$shopSlug'
import { Route as ProductsProductSlugRouteImport } from './routes/products/$productSlug'
import { Route as OrdersPlatformOrderIdRouteImport } from './routes/orders.$platformOrderId'
import { Route as DisputesDisputeIdRouteImport } from './routes/disputes.$disputeId'
import { Route as CreatorShopRouteImport } from './routes/creator/shop'
import { Route as CreatorProductsRouteImport } from './routes/creator/products'
import { Route as CreatorPayoutsRouteImport } from './routes/creator/payouts'
import { Route as CategoryAllRouteImport } from './routes/category/all'
import { Route as CategorySlugRouteImport } from './routes/category/$slug'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as AdminShopsRouteImport } from './routes/admin/shops'
import { Route as AdminPayoutsRouteImport } from './routes/admin/payouts'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminDisputesRouteImport } from './routes/admin/disputes'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as CreatorProductsIndexRouteImport } from './routes/creator/products/index'
import { Route as StudioShopIdOrdersRouteImport } from './routes/studio/$shopId.orders'
import { Route as OrdersPlatformOrderIdSuccessRouteImport } from './routes/orders.$platformOrderId.success'
import { Route as CreatorProductsNewRouteImport } from './routes/creator/products/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminOrdersPlatformOrderIdRouteImport } from './routes/admin/orders.$platformOrderId'
import { Route as AdminDisputesDisputeIdRouteImport } from './routes/admin/disputes/$disputeId'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders.$orderId'
import { Route as StudioShopIdOrdersShopOrderIdRouteImport } from './routes/studio/$shopId.orders.$shopOrderId'
import { Route as CreatorProductsProductIdEditRouteImport } from './routes/creator/products/$productId/edit'
import { Route as ApiShopsShopIdSettingsRouteImport } from './routes/api/shops/$shopId/settings'
import { Route as ApiShopsShopIdProductsRouteImport } from './routes/api/shops/$shopId/products'
import { Route as ApiShopsShopIdOrdersRouteImport } from './routes/api/shops/$shopId/orders'
import { Route as ApiShopsShopIdDashboardRouteImport } from './routes/api/shops/$shopId/dashboard'
import { Route as ApiAdminPayoutsPayoutIdRouteImport } from './routes/api/admin/payouts.$payoutId'
import { Route as ApiShopsShopIdProductsProductIdRouteImport } from './routes/api/shops/$shopId/products.$productId'
import { Route as ApiShopsShopIdOrdersShopOrderIdRouteImport } from './routes/api/shops/$shopId/orders.$shopOrderId'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/studio/',
  path: '/studio/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/account/',
  path: '/account/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioShopIdRoute = StudioShopIdRouteImport.update({
  id: '/studio/$shopId',
  path: '/studio/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopSlugRoute = ShopsShopSlugRouteImport.update({
  id: '/shops/$shopSlug',
  path: '/shops/$shopSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductSlugRoute = ProductsProductSlugRouteImport.update({
  id: '/products/$productSlug',
  path: '/products/$productSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersPlatformOrderIdRoute = OrdersPlatformOrderIdRouteImport.update({
  id: '/$platformOrderId',
  path: '/$platformOrderId',
  getParentRoute: () => OrdersRoute,
} as any)
const DisputesDisputeIdRoute = DisputesDisputeIdRouteImport.update({
  id: '/disputes/$disputeId',
  path: '/disputes/$disputeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorShopRoute = CreatorShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProductsRoute = CreatorProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorPayoutsRoute = CreatorPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => CreatorRoute,
} as any)
const CategoryAllRoute = CategoryAllRouteImport.update({
  id: '/category/all',
  path: '/category/all',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShopsRoute = AdminShopsRouteImport.update({
  id: '/admin/shops',
  path: '/admin/shops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/admin/payouts',
  path: '/admin/payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/admin/disputes',
  path: '/admin/disputes',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorProductsIndexRoute = CreatorProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorProductsRoute,
} as any)
const StudioShopIdOrdersRoute = StudioShopIdOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => StudioShopIdRoute,
} as any)
const OrdersPlatformOrderIdSuccessRoute =
  OrdersPlatformOrderIdSuccessRouteImport.update({
    id: '/success',
    path: '/success',
    getParentRoute: () => OrdersPlatformOrderIdRoute,
  } as any)
const CreatorProductsNewRoute = CreatorProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CreatorProductsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersPlatformOrderIdRoute =
  AdminOrdersPlatformOrderIdRouteImport.update({
    id: '/$platformOrderId',
    path: '/$platformOrderId',
    getParentRoute: () => AdminOrdersRoute,
  } as any)
const AdminDisputesDisputeIdRoute = AdminDisputesDisputeIdRouteImport.update({
  id: '/$disputeId',
  path: '/$disputeId',
  getParentRoute: () => AdminDisputesRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const StudioShopIdOrdersShopOrderIdRoute =
  StudioShopIdOrdersShopOrderIdRouteImport.update({
    id: '/$shopOrderId',
    path: '/$shopOrderId',
    getParentRoute: () => StudioShopIdOrdersRoute,
  } as any)
const CreatorProductsProductIdEditRoute =
  CreatorProductsProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => CreatorProductsRoute,
  } as any)
const ApiShopsShopIdSettingsRoute = ApiShopsShopIdSettingsRouteImport.update({
  id: '/api/shops/$shopId/settings',
  path: '/api/shops/$shopId/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopsShopIdProductsRoute = ApiShopsShopIdProductsRouteImport.update({
  id: '/api/shops/$shopId/products',
  path: '/api/shops/$shopId/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopsShopIdOrdersRoute = ApiShopsShopIdOrdersRouteImport.update({
  id: '/api/shops/$shopId/orders',
  path: '/api/shops/$shopId/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopsShopIdDashboardRoute = ApiShopsShopIdDashboardRouteImport.update({
  id: '/api/shops/$shopId/dashboard',
  path: '/api/shops/$shopId/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminPayoutsPayoutIdRoute = ApiAdminPayoutsPayoutIdRouteImport.update({
  id: '/api/admin/payouts/$payoutId',
  path: '/api/admin/payouts/$payoutId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShopsShopIdProductsProductIdRoute =
  ApiShopsShopIdProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => ApiShopsShopIdProductsRoute,
  } as any)
const ApiShopsShopIdOrdersShopOrderIdRoute =
  ApiShopsShopIdOrdersShopOrderIdRouteImport.update({
    id: '/$shopOrderId',
    path: '/$shopOrderId',
    getParentRoute: () => ApiShopsShopIdOrdersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/api/products': typeof ApiProductsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/category/all': typeof CategoryAllRoute
  '/creator/payouts': typeof CreatorPayoutsRoute
  '/creator/products': typeof CreatorProductsRouteWithChildren
  '/creator/shop': typeof CreatorShopRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/orders/$platformOrderId': typeof OrdersPlatformOrderIdRouteWithChildren
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/shops/$shopSlug': typeof ShopsShopSlugRoute
  '/sitemap.xml': typeof SitemapXmlRoute
  '/studio/$shopId': typeof StudioShopIdRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/orders/$platformOrderId': typeof AdminOrdersPlatformOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/creator/products/new': typeof CreatorProductsNewRoute
  '/orders/$platformOrderId/success': typeof OrdersPlatformOrderIdSuccessRoute
  '/studio/$shopId/orders': typeof StudioShopIdOrdersRouteWithChildren
  '/creator/products/': typeof CreatorProductsIndexRoute
  '/api/admin/payouts/$payoutId': typeof ApiAdminPayoutsPayoutIdRoute
  '/api/shops/$shopId/dashboard': typeof ApiShopsShopIdDashboardRoute
  '/api/shops/$shopId/orders': typeof ApiShopsShopIdOrdersRouteWithChildren
  '/api/shops/$shopId/products': typeof ApiShopsShopIdProductsRouteWithChildren
  '/api/shops/$shopId/settings': typeof ApiShopsShopIdSettingsRoute
  '/creator/products/$productId/edit': typeof CreatorProductsProductIdEditRoute
  '/studio/$shopId/orders/$shopOrderId': typeof StudioShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/orders/$shopOrderId': typeof ApiShopsShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/products/$productId': typeof ApiShopsShopIdProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/api/products': typeof ApiProductsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/category/all': typeof CategoryAllRoute
  '/creator/payouts': typeof CreatorPayoutsRoute
  '/creator/shop': typeof CreatorShopRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/orders/$platformOrderId': typeof OrdersPlatformOrderIdRouteWithChildren
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/shops/$shopSlug': typeof ShopsShopSlugRoute
  '/sitemap.xml': typeof SitemapXmlRoute
  '/studio/$shopId': typeof StudioShopIdRouteWithChildren
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/studio': typeof StudioIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/orders/$platformOrderId': typeof AdminOrdersPlatformOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/creator/products/new': typeof CreatorProductsNewRoute
  '/orders/$platformOrderId/success': typeof OrdersPlatformOrderIdSuccessRoute
  '/studio/$shopId/orders': typeof StudioShopIdOrdersRouteWithChildren
  '/creator/products': typeof CreatorProductsIndexRoute
  '/api/admin/payouts/$payoutId': typeof ApiAdminPayoutsPayoutIdRoute
  '/api/shops/$shopId/dashboard': typeof ApiShopsShopIdDashboardRoute
  '/api/shops/$shopId/orders': typeof ApiShopsShopIdOrdersRouteWithChildren
  '/api/shops/$shopId/products': typeof ApiShopsShopIdProductsRouteWithChildren
  '/api/shops/$shopId/settings': typeof ApiShopsShopIdSettingsRoute
  '/creator/products/$productId/edit': typeof CreatorProductsProductIdEditRoute
  '/studio/$shopId/orders/$shopOrderId': typeof StudioShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/orders/$shopOrderId': typeof ApiShopsShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/products/$productId': typeof ApiShopsShopIdProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/creator': typeof CreatorRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/notifications': typeof NotificationsRoute
  '/orders': typeof OrdersRouteWithChildren
  '/search': typeof SearchRoute
  '/signin': typeof SigninRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRoute
  '/admin/shops': typeof AdminShopsRoute
  '/api/products': typeof ApiProductsRoute
  '/category/$slug': typeof CategorySlugRoute
  '/category/all': typeof CategoryAllRoute
  '/creator/payouts': typeof CreatorPayoutsRoute
  '/creator/products': typeof CreatorProductsRouteWithChildren
  '/creator/shop': typeof CreatorShopRoute
  '/disputes/$disputeId': typeof DisputesDisputeIdRoute
  '/orders/$platformOrderId': typeof OrdersPlatformOrderIdRouteWithChildren
  '/products/$productSlug': typeof ProductsProductSlugRoute
  '/shops/$shopSlug': typeof ShopsShopSlugRoute
  '/sitemap.xml': typeof SitemapXmlRoute
  '/studio/$shopId': typeof StudioShopIdRouteWithChildren
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/admin/disputes/$disputeId': typeof AdminDisputesDisputeIdRoute
  '/admin/orders/$platformOrderId': typeof AdminOrdersPlatformOrderIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/creator/products/new': typeof CreatorProductsNewRoute
  '/orders/$platformOrderId/success': typeof OrdersPlatformOrderIdSuccessRoute
  '/studio/$shopId/orders': typeof StudioShopIdOrdersRouteWithChildren
  '/creator/products/': typeof CreatorProductsIndexRoute
  '/api/admin/payouts/$payoutId': typeof ApiAdminPayoutsPayoutIdRoute
  '/api/shops/$shopId/dashboard': typeof ApiShopsShopIdDashboardRoute
  '/api/shops/$shopId/orders': typeof ApiShopsShopIdOrdersRouteWithChildren
  '/api/shops/$shopId/products': typeof ApiShopsShopIdProductsRouteWithChildren
  '/api/shops/$shopId/settings': typeof ApiShopsShopIdSettingsRoute
  '/creator/products/$productId/edit': typeof CreatorProductsProductIdEditRoute
  '/studio/$shopId/orders/$shopOrderId': typeof StudioShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/orders/$shopOrderId': typeof ApiShopsShopIdOrdersShopOrderIdRoute
  '/api/shops/$shopId/products/$productId': typeof ApiShopsShopIdProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/creator'
    | '/forbidden'
    | '/notifications'
    | '/orders'
    | '/search'
    | '/signin'
    | '/account/orders'
    | '/account/settings'
    | '/admin/disputes'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/shops'
    | '/api/products'
    | '/category/$slug'
    | '/category/all'
    | '/creator/payouts'
    | '/creator/products'
    | '/creator/shop'
    | '/disputes/$disputeId'
    | '/orders/$platformOrderId'
    | '/products/$productSlug'
    | '/shops/$shopSlug'
    | '/sitemap.xml'
    | '/studio/$shopId'
    | '/account/'
    | '/admin/'
    | '/studio/'
    | '/account/orders/$orderId'
    | '/admin/disputes/$disputeId'
    | '/admin/orders/$platformOrderId'
    | '/api/auth/$'
    | '/creator/products/new'
    | '/orders/$platformOrderId/success'
    | '/studio/$shopId/orders'
    | '/creator/products/'
    | '/api/admin/payouts/$payoutId'
    | '/api/shops/$shopId/dashboard'
    | '/api/shops/$shopId/orders'
    | '/api/shops/$shopId/products'
    | '/api/shops/$shopId/settings'
    | '/creator/products/$productId/edit'
    | '/studio/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/creator'
    | '/forbidden'
    | '/notifications'
    | '/orders'
    | '/search'
    | '/signin'
    | '/account/orders'
    | '/account/settings'
    | '/admin/disputes'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/shops'
    | '/api/products'
    | '/category/$slug'
    | '/category/all'
    | '/creator/payouts'
    | '/creator/shop'
    | '/disputes/$disputeId'
    | '/orders/$platformOrderId'
    | '/products/$productSlug'
    | '/shops/$shopSlug'
    | '/sitemap.xml'
    | '/studio/$shopId'
    | '/account'
    | '/admin'
    | '/studio'
    | '/account/orders/$orderId'
    | '/admin/disputes/$disputeId'
    | '/admin/orders/$platformOrderId'
    | '/api/auth/$'
    | '/creator/products/new'
    | '/orders/$platformOrderId/success'
    | '/studio/$shopId/orders'
    | '/creator/products'
    | '/api/admin/payouts/$payoutId'
    | '/api/shops/$shopId/dashboard'
    | '/api/shops/$shopId/orders'
    | '/api/shops/$shopId/products'
    | '/api/shops/$shopId/settings'
    | '/creator/products/$productId/edit'
    | '/studio/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/products/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/creator'
    | '/forbidden'
    | '/notifications'
    | '/orders'
    | '/search'
    | '/signin'
    | '/account/orders'
    | '/account/settings'
    | '/admin/disputes'
    | '/admin/orders'
    | '/admin/payouts'
    | '/admin/shops'
    | '/api/products'
    | '/category/$slug'
    | '/category/all'
    | '/creator/payouts'
    | '/creator/products'
    | '/creator/shop'
    | '/disputes/$disputeId'
    | '/orders/$platformOrderId'
    | '/products/$productSlug'
    | '/shops/$shopSlug'
    | '/sitemap.xml'
    | '/studio/$shopId'
    | '/account/'
    | '/admin/'
    | '/studio/'
    | '/account/orders/$orderId'
    | '/admin/disputes/$disputeId'
    | '/admin/orders/$platformOrderId'
    | '/api/auth/$'
    | '/creator/products/new'
    | '/orders/$platformOrderId/success'
    | '/studio/$shopId/orders'
    | '/creator/products/'
    | '/api/admin/payouts/$payoutId'
    | '/api/shops/$shopId/dashboard'
    | '/api/shops/$shopId/orders'
    | '/api/shops/$shopId/products'
    | '/api/shops/$shopId/settings'
    | '/creator/products/$productId/edit'
    | '/studio/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/orders/$shopOrderId'
    | '/api/shops/$shopId/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CreatorRoute: typeof CreatorRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  NotificationsRoute: typeof NotificationsRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  SearchRoute: typeof SearchRoute
  SigninRoute: typeof SigninRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountSettingsRoute: typeof AccountSettingsRoute
  AdminDisputesRoute: typeof AdminDisputesRouteWithChildren
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPayoutsRoute: typeof AdminPayoutsRoute
  AdminShopsRoute: typeof AdminShopsRoute
  ApiProductsRoute: typeof ApiProductsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  CategoryAllRoute: typeof CategoryAllRoute
  DisputesDisputeIdRoute: typeof DisputesDisputeIdRoute
  ProductsProductSlugRoute: typeof ProductsProductSlugRoute
  ShopsShopSlugRoute: typeof ShopsShopSlugRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  StudioShopIdRoute: typeof StudioShopIdRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StudioIndexRoute: typeof StudioIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAdminPayoutsPayoutIdRoute: typeof ApiAdminPayoutsPayoutIdRoute
  ApiShopsShopIdDashboardRoute: typeof ApiShopsShopIdDashboardRoute
  ApiShopsShopIdOrdersRoute: typeof ApiShopsShopIdOrdersRouteWithChildren
  ApiShopsShopIdProductsRoute: typeof ApiShopsShopIdProductsRouteWithChildren
  ApiShopsShopIdSettingsRoute: typeof ApiShopsShopIdSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/studio'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/': {
      id: '/account/'
      path: '/account'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/$shopId': {
      id: '/studio/$shopId'
      path: '/studio/$shopId'
      fullPath: '/studio/$shopId'
      preLoaderRoute: typeof StudioShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopSlug': {
      id: '/shops/$shopSlug'
      path: '/shops/$shopSlug'
      fullPath: '/shops/$shopSlug'
      preLoaderRoute: typeof ShopsShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productSlug': {
      id: '/products/$productSlug'
      path: '/products/$productSlug'
      fullPath: '/products/$productSlug'
      preLoaderRoute: typeof ProductsProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$platformOrderId': {
      id: '/orders/$platformOrderId'
      path: '/$platformOrderId'
      fullPath: '/orders/$platformOrderId'
      preLoaderRoute: typeof OrdersPlatformOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/disputes/$disputeId': {
      id: '/disputes/$disputeId'
      path: '/disputes/$disputeId'
      fullPath: '/disputes/$disputeId'
      preLoaderRoute: typeof DisputesDisputeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/shop': {
      id: '/creator/shop'
      path: '/shop'
      fullPath: '/creator/shop'
      preLoaderRoute: typeof CreatorShopRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/products': {
      id: '/creator/products'
      path: '/products'
      fullPath: '/creator/products'
      preLoaderRoute: typeof CreatorProductsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/payouts': {
      id: '/creator/payouts'
      path: '/payouts'
      fullPath: '/creator/payouts'
      preLoaderRoute: typeof CreatorPayoutsRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/category/all': {
      id: '/category/all'
      path: '/category/all'
      fullPath: '/category/all'
      preLoaderRoute: typeof CategoryAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/shops': {
      id: '/admin/shops'
      path: '/admin/shops'
      fullPath: '/admin/shops'
      preLoaderRoute: typeof AdminShopsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/admin/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/products/': {
      id: '/creator/products/'
      path: '/'
      fullPath: '/creator/products/'
      preLoaderRoute: typeof CreatorProductsIndexRouteImport
      parentRoute: typeof CreatorProductsRoute
    }
    '/studio/$shopId/orders': {
      id: '/studio/$shopId/orders'
      path: '/orders'
      fullPath: '/studio/$shopId/orders'
      preLoaderRoute: typeof StudioShopIdOrdersRouteImport
      parentRoute: typeof StudioShopIdRoute
    }
    '/orders/$platformOrderId/success': {
      id: '/orders/$platformOrderId/success'
      path: '/success'
      fullPath: '/orders/$platformOrderId/success'
      preLoaderRoute: typeof OrdersPlatformOrderIdSuccessRouteImport
      parentRoute: typeof OrdersPlatformOrderIdRoute
    }
    '/creator/products/new': {
      id: '/creator/products/new'
      path: '/new'
      fullPath: '/creator/products/new'
      preLoaderRoute: typeof CreatorProductsNewRouteImport
      parentRoute: typeof CreatorProductsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$platformOrderId': {
      id: '/admin/orders/$platformOrderId'
      path: '/$platformOrderId'
      fullPath: '/admin/orders/$platformOrderId'
      preLoaderRoute: typeof AdminOrdersPlatformOrderIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/disputes/$disputeId': {
      id: '/admin/disputes/$disputeId'
      path: '/$disputeId'
      fullPath: '/admin/disputes/$disputeId'
      preLoaderRoute: typeof AdminDisputesDisputeIdRouteImport
      parentRoute: typeof AdminDisputesRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/studio/$shopId/orders/$shopOrderId': {
      id: '/studio/$shopId/orders/$shopOrderId'
      path: '/$shopOrderId'
      fullPath: '/studio/$shopId/orders/$shopOrderId'
      preLoaderRoute: typeof StudioShopIdOrdersShopOrderIdRouteImport
      parentRoute: typeof StudioShopIdOrdersRoute
    }
    '/creator/products/$productId/edit': {
      id: '/creator/products/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/creator/products/$productId/edit'
      preLoaderRoute: typeof CreatorProductsProductIdEditRouteImport
      parentRoute: typeof CreatorProductsRoute
    }
    '/api/shops/$shopId/settings': {
      id: '/api/shops/$shopId/settings'
      path: '/api/shops/$shopId/settings'
      fullPath: '/api/shops/$shopId/settings'
      preLoaderRoute: typeof ApiShopsShopIdSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shops/$shopId/products': {
      id: '/api/shops/$shopId/products'
      path: '/api/shops/$shopId/products'
      fullPath: '/api/shops/$shopId/products'
      preLoaderRoute: typeof ApiShopsShopIdProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shops/$shopId/orders': {
      id: '/api/shops/$shopId/orders'
      path: '/api/shops/$shopId/orders'
      fullPath: '/api/shops/$shopId/orders'
      preLoaderRoute: typeof ApiShopsShopIdOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shops/$shopId/dashboard': {
      id: '/api/shops/$shopId/dashboard'
      path: '/api/shops/$shopId/dashboard'
      fullPath: '/api/shops/$shopId/dashboard'
      preLoaderRoute: typeof ApiShopsShopIdDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/payouts/$payoutId': {
      id: '/api/admin/payouts/$payoutId'
      path: '/api/admin/payouts/$payoutId'
      fullPath: '/api/admin/payouts/$payoutId'
      preLoaderRoute: typeof ApiAdminPayoutsPayoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shops/$shopId/products/$productId': {
      id: '/api/shops/$shopId/products/$productId'
      path: '/$productId'
      fullPath: '/api/shops/$shopId/products/$productId'
      preLoaderRoute: typeof ApiShopsShopIdProductsProductIdRouteImport
      parentRoute: typeof ApiShopsShopIdProductsRoute
    }
    '/api/shops/$shopId/orders/$shopOrderId': {
      id: '/api/shops/$shopId/orders/$shopOrderId'
      path: '/$shopOrderId'
      fullPath: '/api/shops/$shopId/orders/$shopOrderId'
      preLoaderRoute: typeof ApiShopsShopIdOrdersShopOrderIdRouteImport
      parentRoute: typeof ApiShopsShopIdOrdersRoute
    }
  }
}

interface CreatorProductsRouteChildren {
  CreatorProductsNewRoute: typeof CreatorProductsNewRoute
  CreatorProductsIndexRoute: typeof CreatorProductsIndexRoute
  CreatorProductsProductIdEditRoute: typeof CreatorProductsProductIdEditRoute
}

const CreatorProductsRouteChildren: CreatorProductsRouteChildren = {
  CreatorProductsNewRoute: CreatorProductsNewRoute,
  CreatorProductsIndexRoute: CreatorProductsIndexRoute,
  CreatorProductsProductIdEditRoute: CreatorProductsProductIdEditRoute,
}

const CreatorProductsRouteWithChildren = CreatorProductsRoute._addFileChildren(
  CreatorProductsRouteChildren,
)

interface CreatorRouteChildren {
  CreatorPayoutsRoute: typeof CreatorPayoutsRoute
  CreatorProductsRoute: typeof CreatorProductsRouteWithChildren
  CreatorShopRoute: typeof CreatorShopRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorPayoutsRoute: CreatorPayoutsRoute,
  CreatorProductsRoute: CreatorProductsRouteWithChildren,
  CreatorShopRoute: CreatorShopRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface OrdersPlatformOrderIdRouteChildren {
  OrdersPlatformOrderIdSuccessRoute: typeof OrdersPlatformOrderIdSuccessRoute
}

const OrdersPlatformOrderIdRouteChildren: OrdersPlatformOrderIdRouteChildren = {
  OrdersPlatformOrderIdSuccessRoute: OrdersPlatformOrderIdSuccessRoute,
}

const OrdersPlatformOrderIdRouteWithChildren =
  OrdersPlatformOrderIdRoute._addFileChildren(
    OrdersPlatformOrderIdRouteChildren,
  )

interface OrdersRouteChildren {
  OrdersPlatformOrderIdRoute: typeof OrdersPlatformOrderIdRouteWithChildren
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersPlatformOrderIdRoute: OrdersPlatformOrderIdRouteWithChildren,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AdminDisputesRouteChildren {
  AdminDisputesDisputeIdRoute: typeof AdminDisputesDisputeIdRoute
}

const AdminDisputesRouteChildren: AdminDisputesRouteChildren = {
  AdminDisputesDisputeIdRoute: AdminDisputesDisputeIdRoute,
}

const AdminDisputesRouteWithChildren = AdminDisputesRoute._addFileChildren(
  AdminDisputesRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersPlatformOrderIdRoute: typeof AdminOrdersPlatformOrderIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersPlatformOrderIdRoute: AdminOrdersPlatformOrderIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface StudioShopIdOrdersRouteChildren {
  StudioShopIdOrdersShopOrderIdRoute: typeof StudioShopIdOrdersShopOrderIdRoute
}

const StudioShopIdOrdersRouteChildren: StudioShopIdOrdersRouteChildren = {
  StudioShopIdOrdersShopOrderIdRoute: StudioShopIdOrdersShopOrderIdRoute,
}

const StudioShopIdOrdersRouteWithChildren =
  StudioShopIdOrdersRoute._addFileChildren(StudioShopIdOrdersRouteChildren)

interface StudioShopIdRouteChildren {
  StudioShopIdOrdersRoute: typeof StudioShopIdOrdersRouteWithChildren
}

const StudioShopIdRouteChildren: StudioShopIdRouteChildren = {
  StudioShopIdOrdersRoute: StudioShopIdOrdersRouteWithChildren,
}

const StudioShopIdRouteWithChildren = StudioShopIdRoute._addFileChildren(
  StudioShopIdRouteChildren,
)

interface ApiShopsShopIdOrdersRouteChildren {
  ApiShopsShopIdOrdersShopOrderIdRoute: typeof ApiShopsShopIdOrdersShopOrderIdRoute
}

const ApiShopsShopIdOrdersRouteChildren: ApiShopsShopIdOrdersRouteChildren = {
  ApiShopsShopIdOrdersShopOrderIdRoute: ApiShopsShopIdOrdersShopOrderIdRoute,
}

const ApiShopsShopIdOrdersRouteWithChildren =
  ApiShopsShopIdOrdersRoute._addFileChildren(ApiShopsShopIdOrdersRouteChildren)

interface ApiShopsShopIdProductsRouteChildren {
  ApiShopsShopIdProductsProductIdRoute: typeof ApiShopsShopIdProductsProductIdRoute
}

const ApiShopsShopIdProductsRouteChildren: ApiShopsShopIdProductsRouteChildren =
  {
    ApiShopsShopIdProductsProductIdRoute: ApiShopsShopIdProductsProductIdRoute,
  }

const ApiShopsShopIdProductsRouteWithChildren =
  ApiShopsShopIdProductsRoute._addFileChildren(
    ApiShopsShopIdProductsRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CreatorRoute: CreatorRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  NotificationsRoute: NotificationsRoute,
  OrdersRoute: OrdersRouteWithChildren,
  SearchRoute: SearchRoute,
  SigninRoute: SigninRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountSettingsRoute: AccountSettingsRoute,
  AdminDisputesRoute: AdminDisputesRouteWithChildren,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPayoutsRoute: AdminPayoutsRoute,
  AdminShopsRoute: AdminShopsRoute,
  ApiProductsRoute: ApiProductsRoute,
  CategorySlugRoute: CategorySlugRoute,
  CategoryAllRoute: CategoryAllRoute,
  DisputesDisputeIdRoute: DisputesDisputeIdRoute,
  ProductsProductSlugRoute: ProductsProductSlugRoute,
  ShopsShopSlugRoute: ShopsShopSlugRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  StudioShopIdRoute: StudioShopIdRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  StudioIndexRoute: StudioIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAdminPayoutsPayoutIdRoute: ApiAdminPayoutsPayoutIdRoute,
  ApiShopsShopIdDashboardRoute: ApiShopsShopIdDashboardRoute,
  ApiShopsShopIdOrdersRoute: ApiShopsShopIdOrdersRouteWithChildren,
  ApiShopsShopIdProductsRoute: ApiShopsShopIdProductsRouteWithChildren,
  ApiShopsShopIdSettingsRoute: ApiShopsShopIdSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
